"""Integration tests for eLabFTW export destination.

These tests run against a real eLabFTW instance in Docker and verify:
- API client CRUD operations
- Export destination workflow
- File uploads
- Cross-linking with CDCS
- Database logging

Requires: docker compose up -d (in tests/integration/docker/)
"""

from datetime import datetime

import pytest
import requests
from sqlmodel import Session as DBSession
from sqlmodel import select

from nexusLIMS.db.models import UploadLog
from nexusLIMS.exporters.base import ExportResult
from nexusLIMS.exporters.destinations.elabftw import ELabFTWDestination
from nexusLIMS.utils.elabftw import (
    ELabFTWAuthenticationError,
    ELabFTWClient,
    State,
)

# eLabFTW service URL (via Caddy proxy)
ELABFTW_URL = "http://elabftw.localhost:40080"

# Test API key (generated by init_elabftw.py)
ELABFTW_API_KEY = "1-" + "a" * 84


# ============================================================================
# Test Fixtures
# ============================================================================


# ============================================================================
# Docker Stack Smoke Tests
# ============================================================================


@pytest.mark.integration
class TestELabFTWDockerStack:
    """Smoke tests for eLabFTW Docker stack setup."""

    def test_elabftw_api_accessible(self, docker_services):
        """Test that eLabFTW API is accessible."""
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            params={"limit": 1},
            timeout=10,
        )
        assert response.status_code == 200
        # Should return a list (may be empty or contain experiments)
        data = response.json()
        assert isinstance(data, list)

    def test_elabftw_api_authentication(self, docker_services):
        """Test that API authentication works."""
        # Test with valid key
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            timeout=10,
        )
        assert response.status_code == 200

        # Test with invalid key
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": "invalid-key"},
            timeout=10,
        )
        assert response.status_code in {401, 403}

    def test_can_create_experiment(self, docker_services):
        """Test creating an experiment via API."""
        response = requests.post(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            json={"title": "Test Experiment", "body": "Test body"},
            timeout=10,
        )
        assert response.status_code == 201
        # Response may be empty or contain the created experiment
        if response.text:
            data = response.json()
            assert "id" in data


# ============================================================================
# API Client Integration Tests
# ============================================================================


@pytest.mark.integration
class TestELabFTWClientIntegration:
    """Integration tests for ELabFTWClient with real API."""

    def test_create_and_get_experiment(self, elabftw_client: ELabFTWClient):
        """Test creating experiment and retrieving it."""
        # Create experiment
        result = elabftw_client.create_experiment(
            title="Integration Test - Create and Get",
            body="Testing create and retrieve operations",
        )

        assert "id" in result
        experiment_id = result["id"]

        # Retrieve experiment
        retrieved = elabftw_client.get_experiment(experiment_id)
        assert retrieved["id"] == experiment_id
        assert retrieved["title"] == "Integration Test - Create and Get"
        assert "Testing create and retrieve" in retrieved["body"]

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_list_experiments(self, elabftw_client: ELabFTWClient):
        """Test listing experiments with pagination."""
        # Create a few experiments
        created_ids = []
        for i in range(3):
            result = elabftw_client.create_experiment(
                title=f"Integration Test - List {i}",
                body=f"Test experiment {i} for listing",
            )
            created_ids.append(result["id"])

        # List all experiments
        experiments = elabftw_client.list_experiments(limit=100)
        assert len(experiments) >= 3

        # Verify our created experiments are in the list
        experiment_ids = {exp["id"] for exp in experiments}
        for created_id in created_ids:
            assert created_id in experiment_ids

        # Test pagination with smaller limit
        page1 = elabftw_client.list_experiments(limit=2, offset=0)
        page2 = elabftw_client.list_experiments(limit=2, offset=2)
        assert len(page1) <= 2
        assert len(page2) <= 2

        # Cleanup
        for exp_id in created_ids:
            elabftw_client.delete_experiment(exp_id)

    def test_update_experiment(self, elabftw_client: ELabFTWClient):
        """Test updating experiment fields."""
        # Create experiment
        result = elabftw_client.create_experiment(
            title="Integration Test - Update Original",
            body="Original body content",
        )
        experiment_id = result["id"]

        # Update title and body
        _ = elabftw_client.update_experiment(
            experiment_id,
            title="Integration Test - Update Modified",
            body="Updated body content",
        )

        # Verify update
        retrieved = elabftw_client.get_experiment(experiment_id)
        assert retrieved["title"] == "Integration Test - Update Modified"
        assert "Updated body content" in retrieved["body"]
        assert retrieved["state"] == State.Normal

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_delete_experiment(self, elabftw_client: ELabFTWClient):
        """Test soft-deleting experiment."""
        # Create experiment
        result = elabftw_client.create_experiment(
            title="Integration Test - Delete",
            body="This will be deleted",
        )
        experiment_id = result["id"]

        # Delete experiment
        elabftw_client.delete_experiment(experiment_id)

        # Verify deletion
        record = elabftw_client.get_experiment(experiment_id)
        assert record["state"] == State.Deleted

    def test_upload_file(self, elabftw_client, tmp_path):
        """Test uploading text and binary files to experiment."""
        # Create experiment
        result = elabftw_client.create_experiment(
            title="Integration Test - File Upload",
            body="Testing file upload",
        )
        experiment_id = result["id"]

        # Create and upload text file
        test_file = tmp_path / "test_upload.txt"
        test_file.write_text("Test file content for upload")

        upload_result = elabftw_client.upload_file_to_experiment(
            experiment_id, str(test_file), comment="Integration test text file"
        )

        assert "id" in upload_result

        # Create and upload binary PNG file using Pillow
        from PIL import Image, ImageDraw

        binary_file = tmp_path / "test_image.png"
        img = Image.new("RGB", (100, 100), color="white")
        draw = ImageDraw.Draw(img)
        # Draw a simple checkerboard pattern
        for i in range(0, 100, 20):
            for j in range(0, 100, 20):
                if (i + j) // 20 % 2 == 0:
                    draw.rectangle([i, j, i + 20, j + 20], fill="red")
        img.save(binary_file)

        binary_upload_result = elabftw_client.upload_file_to_experiment(
            experiment_id, str(binary_file), comment="Integration test binary file"
        )

        assert "id" in binary_upload_result

        # Retrieve experiment and verify both files are attached
        retrieved = elabftw_client.get_experiment(experiment_id)
        assert "uploads" in retrieved
        assert len(retrieved["uploads"]) >= 2

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_create_with_tags_and_metadata(
        self, elabftw_client: ELabFTWClient, export_context_elabftw
    ):
        """Test creating experiment with tags and extra_fields metadata."""
        # Build metadata using the destination's method
        destination = ELabFTWDestination()
        metadata = destination._build_metadata(export_context_elabftw)  # noqa: SLF001

        # Create experiment with tags and extra_fields metadata
        # Note: Using "NexusLIMS" with proper capitalization because eLabFTW
        # normalizes tag capitalization to match existing tags in the database.
        # Previous tests (via destination.export()) create the "NexusLIMS" tag,
        # so eLabFTW will normalize "nexuslims" -> "NexusLIMS".
        result = elabftw_client.create_experiment(
            title="Integration Test - Tags and Metadata",
            body="Testing tags and metadata",
            tags=["integration", "test", "NexusLIMS"],
            metadata=metadata,
        )

        experiment_id = result["id"]

        # Retrieve and verify
        retrieved = elabftw_client.get_experiment(experiment_id)
        assert retrieved["id"] == experiment_id

        # Verify tags
        # Note: eLabFTW API returns tags as pipe-separated string, but our client
        # automatically converts it to a list for convenience
        tags_field = retrieved.get("tags", [])
        assert isinstance(tags_field, list), (
            f"Expected tags as list, got {type(tags_field)}"
        )

        # All tags should be present (use set comparison to ignore order)
        expected_tags = {"integration", "test", "NexusLIMS"}
        actual_tags = set(tags_field)
        assert expected_tags == actual_tags, (
            f"Expected tags {expected_tags}, got {actual_tags}"
        )

        # Verify metadata - client automatically parses JSON string to dict
        metadata = retrieved.get("metadata", {})
        assert metadata, "Metadata should be present"
        assert isinstance(metadata, dict), (
            f"Expected metadata as dict, got {type(metadata)}"
        )

        # Verify extra_fields structure and values
        assert "extra_fields" in metadata, "Metadata should contain extra_fields"
        extra_fields = metadata["extra_fields"]
        assert isinstance(extra_fields, dict), "extra_fields should be a dict"

        # Verify Session ID field
        assert "Session ID" in extra_fields
        session_field = extra_fields["Session ID"]
        assert session_field["type"] == "text"
        assert session_field["value"] == "integration-test-2025-01-27"

        # Verify Instrument field
        assert "Instrument" in extra_fields
        instrument_field = extra_fields["Instrument"]
        assert instrument_field["type"] == "text"
        assert instrument_field["value"] == "FEI-Titan-TEM"

        # Verify Start Time field
        assert "Start Time" in extra_fields
        start_field = extra_fields["Start Time"]
        assert start_field["type"] == "datetime-local"
        assert start_field["value"] == "2018-11-13T04:00"

        # Verify End Time field
        assert "End Time" in extra_fields
        end_field = extra_fields["End Time"]
        assert end_field["type"] == "datetime-local"
        assert end_field["value"] == "2018-11-13T16:00"

        # Verify User field
        assert "User" in extra_fields
        user_field = extra_fields["User"]
        assert user_field["type"] == "text"
        assert user_field["value"] == "captain"

        # Verify elabftw config
        assert "elabftw" in metadata
        elabftw_config = metadata["elabftw"]
        assert elabftw_config["display_main_text"] is True
        assert len(elabftw_config["extra_fields_groups"]) >= 1

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_authentication_error(self):
        """Test that invalid credentials raise authentication error."""
        bad_client = ELabFTWClient(base_url=ELABFTW_URL, api_key="invalid-key-12345")

        with pytest.raises(ELabFTWAuthenticationError):
            bad_client.create_experiment(
                title="Should Fail", body="Invalid credentials"
            )


# ============================================================================
# Export Destination Integration Tests
# ============================================================================


@pytest.mark.integration
class TestELabFTWDestinationIntegration:
    """Integration tests for ELabFTWDestination export workflow."""

    def test_export_creates_experiment(
        self, export_context_elabftw, elabftw_client: ELabFTWClient
    ):
        """Test export workflow creates experiment in eLabFTW."""
        destination = ELabFTWDestination()

        # Verify destination is enabled
        assert destination.enabled is True

        # Export record
        result = destination.export(export_context_elabftw)

        # Verify success
        assert result.success is True
        assert result.record_id is not None
        assert (
            result.record_url
            == f"http://elabftw.localhost:40080/experiments.php?mode=view&id={result.record_id}"
        )

        # Verify experiment was created
        experiment_id = int(result.record_id)
        experiment = elabftw_client.get_experiment(experiment_id)
        assert experiment["id"] == experiment_id
        assert experiment["title"] == "NexusLIMS Experiment - integration_test_record"

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_export_uploads_xml_attachment(
        self, export_context_elabftw, elabftw_client: ELabFTWClient
    ):
        """Test XML file attached to experiment."""
        destination = ELabFTWDestination()

        # Export record
        result = destination.export(export_context_elabftw)
        assert result.success is True
        assert result.record_id is not None

        # Retrieve experiment and verify attachment
        experiment_id = int(result.record_id)
        experiment = elabftw_client.get_experiment(experiment_id)

        assert "uploads" in experiment
        assert len(experiment["uploads"]) > 0

        # Find XML attachment
        xml_upload = None
        for upload in experiment["uploads"]:
            if upload.get("real_name", "").endswith(".xml"):
                xml_upload = upload
                break

        assert xml_upload is not None, "XML file not found in uploads"
        assert "integration_test_record.xml" in xml_upload["real_name"]

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_export_with_cdcs_crosslink(
        self, export_context_elabftw, elabftw_client: ELabFTWClient
    ):
        """Test CDCS URL appears in experiment body."""
        destination = ELabFTWDestination()

        # Add a mock CDCS result to the context
        cdcs_result = ExportResult(
            destination_name="cdcs",
            success=True,
            timestamp=datetime.now(),
            record_id="test-cdcs-record-123",
            record_url="http://cdcs.localhost:40080/data/test-cdcs-record-123",
        )
        export_context_elabftw.add_result("cdcs", cdcs_result)

        # Export record
        result = destination.export(export_context_elabftw)
        assert result.success is True

        # Verify CDCS link in body
        experiment_id = int(result.record_id)
        experiment = elabftw_client.get_experiment(experiment_id)

        body = experiment["body"]
        assert "CDCS" in body or "cdcs" in body.lower()
        assert "test-cdcs-record-123" in body or cdcs_result.record_url in body

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_export_logs_to_database(
        self,
        export_context_elabftw,
        test_environment_setup,
        elabftw_client,
        monkeypatch,
    ):
        """Test UploadLog entry created for export."""
        from nexusLIMS.db.engine import get_engine
        from nexusLIMS.db.session_handler import Session
        from nexusLIMS.exporters import export_records

        # Create a Session object for export_records
        instrument = test_environment_setup["instrument_db"][
            test_environment_setup["instrument_pid"]
        ]
        session = Session(
            session_identifier=export_context_elabftw.session_identifier,
            instrument=instrument,
            dt_range=(export_context_elabftw.dt_from, export_context_elabftw.dt_to),
            user=export_context_elabftw.user,
        )

        # Patch registry to only include eLabFTW destination
        # (prevents CDCS export attempts during this test)
        elabftw_dest = ELabFTWDestination()

        def mock_get_enabled():
            return [elabftw_dest]

        from nexusLIMS.exporters import registry as registry_module

        monkeypatch.setattr(
            registry_module.ExporterRegistry,
            "get_enabled_destinations",
            lambda _: mock_get_enabled(),
        )

        # Export using the full framework (which handles database logging)
        results = export_records(
            xml_files=[export_context_elabftw.xml_file_path],
            sessions=[session],
        )

        # Get the export results for our file
        file_results = results[export_context_elabftw.xml_file_path]
        assert len(file_results) > 0

        # Find eLabFTW result (there should only be one, but still check)
        elabftw_result = None
        for result in file_results:
            if result.destination_name == "elabftw":
                elabftw_result = result
                break

        assert elabftw_result is not None, "eLabFTW export not found in results"
        assert elabftw_result.success is True
        assert elabftw_result.record_id is not None

        # Query UploadLog table
        with DBSession(get_engine()) as db_session:
            statement = select(UploadLog).where(
                UploadLog.session_identifier
                == export_context_elabftw.session_identifier
            )
            upload_logs = db_session.exec(statement).all()

            # Should have at least one log entry
            assert len(upload_logs) > 0

            # Find eLabFTW log entry (there should only be one, but still check)
            elabftw_log = None
            for log in upload_logs:
                if log.destination_name == "elabftw":
                    elabftw_log = log
                    break

            assert elabftw_log is not None, "eLabFTW upload log not found"
            assert elabftw_log.success is True
            assert elabftw_log.record_id == elabftw_result.record_id

        # Cleanup
        elabftw_client.delete_experiment(int(elabftw_result.record_id))

    def test_export_handles_missing_xml_file(self, export_context_elabftw):
        """Test export handles missing XML file gracefully."""
        destination = ELabFTWDestination()

        # Delete the XML file
        export_context_elabftw.xml_file_path.unlink()

        # Export should fail gracefully
        result = destination.export(export_context_elabftw)

        assert result.success is False
        assert result.error_message is not None
        assert "File not found" in result.error_message

    def test_validate_config_success(self, elabftw_client, monkeypatch):
        """Test configuration validation with valid credentials."""
        # Configure environment
        monkeypatch.setenv("NX_ELABFTW_URL", ELABFTW_URL)
        monkeypatch.setenv("NX_ELABFTW_API_KEY", ELABFTW_API_KEY)

        from nexusLIMS.config import refresh_settings

        refresh_settings()

        destination = ELabFTWDestination()

        # Validate config
        is_valid, error_message = destination.validate_config()

        assert is_valid is True
        assert error_message is None

    def test_validate_config_invalid_credentials(self, monkeypatch):
        """Test configuration validation with invalid credentials."""
        # Configure with invalid credentials
        monkeypatch.setenv("NX_ELABFTW_URL", ELABFTW_URL)
        monkeypatch.setenv("NX_ELABFTW_API_KEY", "invalid-key-12345")

        from nexusLIMS.config import refresh_settings

        refresh_settings()

        destination = ELabFTWDestination()

        # Validate config
        is_valid, error_message = destination.validate_config()

        assert is_valid is False
        assert error_message is not None
        assert "authentication" in error_message.lower() or "401" in error_message


# ============================================================================
# End-to-End Integration Tests
# ============================================================================


@pytest.mark.integration
# ============================================================================
# Extra Fields Integration Tests
# ============================================================================


@pytest.mark.integration
class TestELabFTWExtraFieldsIntegration:
    """Integration tests for eLabFTW extra_fields schema."""

    def test_create_experiment_with_extra_fields(self, elabftw_client: ELabFTWClient):
        """Test creating experiment with extra_fields metadata."""
        # Create experiment with extra_fields
        result = elabftw_client.create_experiment(
            title="Integration Test - Extra Fields",
            body="Testing extra_fields schema",
            metadata={
                "extra_fields": {
                    "Session ID": {
                        "type": "text",
                        "value": "test-session-12345",
                        "description": "Test session identifier",
                        "position": 1,
                        "group_id": 1,
                    },
                    "Start Time": {
                        "type": "datetime-local",
                        "value": "2025-01-27T10:30",
                        "description": "Session start time",
                        "position": 2,
                        "group_id": 1,
                    },
                    "CDCS Link": {
                        "type": "url",
                        "value": "https://cdcs.example.com/record/123",
                        "description": "Link to CDCS record",
                        "position": 3,
                        "group_id": 2,
                    },
                },
                "elabftw": {
                    "display_main_text": True,
                    "extra_fields_groups": [
                        {"id": 1, "name": "Session Information"},
                        {"id": 2, "name": "Related Records"},
                    ],
                },
            },
        )

        assert "id" in result
        experiment_id = result["id"]

        # Retrieve experiment and verify metadata
        retrieved = elabftw_client.get_experiment(experiment_id)
        assert retrieved["id"] == experiment_id

        # Verify metadata was stored (structure depends on eLabFTW version)
        metadata = retrieved.get("metadata", {})
        assert "elabftw" in metadata
        assert "extra_fields" in metadata

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_export_destination_creates_extra_fields(
        self, export_context_elabftw, elabftw_client: ELabFTWClient
    ):
        """Test export destination creates experiments with extra_fields."""
        destination = ELabFTWDestination()

        # Export record
        result = destination.export(export_context_elabftw)
        assert result.success is True

        # Retrieve experiment
        experiment_id = int(result.record_id)
        experiment = elabftw_client.get_experiment(experiment_id)

        # Verify experiment was created
        assert experiment["id"] == experiment_id
        assert "NexusLIMS" in experiment["title"]

        # Verify metadata contains extra_fields structure
        metadata = experiment.get("metadata", {})
        assert "elabftw" in metadata
        assert "extra_fields" in metadata

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_extra_fields_url_type(self, elabftw_client: ELabFTWClient):
        """Test URL fields are stored correctly."""
        test_url = "https://cdcs.localhost:40080/data/test-record"

        result = elabftw_client.create_experiment(
            title="Integration Test - URL Field",
            metadata={
                "extra_fields": {
                    "CDCS Record": {
                        "type": "url",
                        "value": test_url,
                        "description": "Link to CDCS",
                    }
                },
                "elabftw": {"display_main_text": True},
            },
        )

        experiment_id = result["id"]

        # Retrieve and verify URL is in metadata
        experiment = elabftw_client.get_experiment(experiment_id)
        metadata = experiment.get("metadata", {})
        assert test_url in metadata["extra_fields"]["CDCS Record"]["value"]

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)

    def test_extra_fields_with_groups(self, elabftw_client: ELabFTWClient):
        """Test extra_fields_groups are stored correctly."""
        result = elabftw_client.create_experiment(
            title="Integration Test - Field Groups",
            metadata={
                "extra_fields": {
                    "Field 1": {
                        "type": "text",
                        "value": "Group 1 Field",
                        "group_id": 1,
                        "position": 1,
                    },
                    "Field 2": {
                        "type": "text",
                        "value": "Group 2 Field",
                        "group_id": 2,
                        "position": 2,
                    },
                },
                "elabftw": {
                    "display_main_text": True,
                    "extra_fields_groups": [
                        {"id": 1, "name": "First Group"},
                        {"id": 2, "name": "Second Group"},
                    ],
                },
            },
        )

        experiment_id = result["id"]

        # Retrieve experiment
        experiment = elabftw_client.get_experiment(experiment_id)
        assert experiment["id"] == experiment_id

        # Cleanup
        elabftw_client.delete_experiment(experiment_id)
