"""Integration tests for eLabFTW export destination.

These tests run against a real eLabFTW instance in Docker and verify:
- API client CRUD operations
- Export destination workflow
- File uploads
- Cross-linking with CDCS
- Database logging

Requires: docker compose up -d (in tests/integration/docker/)
"""

import pytest
import requests

# eLabFTW service URL (via Caddy proxy)
ELABFTW_URL = "http://elabftw.localhost:40080"

# Test API key (generated by init_elabftw.py)
ELABFTW_API_KEY = "1-" + "a" * 84


@pytest.mark.integration
class TestELabFTWDockerStack:
    """Smoke tests for eLabFTW Docker stack setup."""

    def test_elabftw_api_accessible(self):
        """Test that eLabFTW API is accessible."""
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            params={"limit": 1},
            timeout=10,
        )
        assert response.status_code == 200
        # Should return a list (may be empty or contain experiments)
        data = response.json()
        assert isinstance(data, list)

    def test_elabftw_api_authentication(self):
        """Test that API authentication works."""
        # Test with valid key
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            timeout=10,
        )
        assert response.status_code == 200

        # Test with invalid key
        response = requests.get(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": "invalid-key"},
            timeout=10,
        )
        assert response.status_code in {401, 403}

    def test_can_create_experiment(self):
        """Test creating an experiment via API."""
        response = requests.post(
            f"{ELABFTW_URL}/api/v2/experiments",
            headers={"Authorization": ELABFTW_API_KEY},
            json={"title": "Test Experiment", "body": "Test body"},
            timeout=10,
        )
        assert response.status_code == 201
        # Response may be empty or contain the created experiment
        if response.text:
            data = response.json()
            assert "id" in data
